Huggingface
SopMeAI/sopme pull request #3
Opened 2023-10-15 22:39 UTC by vornsami

API-yhteys sekä  huggingfacen inference API:iin että OpenAI:n API:iin. Huggingface, vastausten kanssa oli testatessa ongelmia, mutta OpenAI:n GPT3.5 toimi odotetusti.

2023-10-16 07:05 UTC, nicholsss approved these changes
LGTM :+1: 
Minkälaisia ongelmia tossa hugginfacessa tuli vastaan?

2023-10-16 08:03 UTC, vornsami commented
Vastaukset katkeaa noin 15 sanan jälkeen

2023-10-20 07:30 UTC, rhiskk requested changes
Jos ei käytetä tot hugging face inference apia, niin sen koodin vois poistaa tästä ennen mergeemistä. Maksulliset API kutsut vois poistaa testeistä, tai kehittää jonkun systeemin millä ne ajetaan vaan jollain tietyllä flagilla tms.

2023-10-20 23:23 UTC, vornsami commented
Huggingface nyt poistettu ja maksulliset kutsut korvattu mockilla.

2023-10-21 14:24 UTC, rhiskk requested changes
Kommentoin noihin tiedostoihin jotain parannusehdotuksia jotka saattais selkeyttää koodia. Kysy jos niissä on jotain epäselvää. Voin kans jeesaa nois tyypityksissä ja muissa jos et ehdi ite nyt perehtyy niihin. Helpottaa vaan jatkossa aika paljon, että tietää minkä tyyppistä dataa mikäkin funktio palauttaa.

2023-10-21 14:24 UTC, rhiskk commented on server/src/services/largeLanguageModel.test.ts
Tää testi dokumentoi ihan hyvin miten tota gptqueryä käytetään ja kun tän ajaa, niin näkee  tosta tulostuksesta mitä se vastaus sisältää. Ekalla kokeilulla tosin tulosti vaan 'Missing API TOKEN', mikä ei välttämättä oo tarpeellista koska näissä testeissä ei sitä API tokenia tarvita. 

**Muutama tyylihuomio:**

Mun mielestä on selkeempi importtaa vaan ne funktiot joita käytetään tyyliin:
```typescript
import { gptquery } from ./largeLanguageModel
```

Toi fs ois kans parempi importtaa tuol testin ulkopuolella. Typescriptissä ei tyypillisesti käytetä tota require() syntaxia vaan importia tähän tyyliin:
```typescript
import fs from 'fs'
```

2023-10-21 14:24 UTC, rhiskk commented on server/src/services/largeLanguageModel.ts
Typescriptissä nimet on yleensä camelCasella eli gptQuery()

Lisäsin tonne mainiin ton env.ts tiedoston jossa validoidaan toi env, ettei tarvitse jokaisen ympristömuuttujan kohdalla varmistaa että se on varmasti olemassa. Jos lisäät sinne ton OPENAI_API_TOKENin samaan tyyliin kun siellä jo olevat muuttujat voit käyttää sitä näin eikä sitä tarvitse validoida enää erikseen: 
```typescript
import { env } from '../env'
const API_TOKEN = env.OPENAI_API_TOKEN
```
Myöskään dotenvia ei sit enään tarvitse tähän tiedostoon importata. 

Toi OpenAi client ois parempi initialisoida ton funktion ulkopuolella jotta sitä ei tarvitse intialisoida turhaan joka funktiokutsun yhteydessä. Tässä vois käyttää ns. dependency injectiota ja antaa ton clientin tolle funktiolle aina muuttujana koska halutaan mahollisuus käyttää testeissä mock clientiä. Mun mielestä hyvä ratkasu tähän ois parametri jonka vakiona on tässä tiedostossa initialisoitu clientti. Tyyliin näin: 
```typescript
const client = new OpenAI...
export async function gptQuery(prompt: string, oai: OpenAI = client)
```
Toi oai ei parametri nimi ei oo myöskään kovin selkee mun mielestä.

Toi return statementti on mun silmään aika sekava. Ois ehkä selkeempi hakee eka se vastaus johonki kuvaavaan muuttujanimeen ja sit palauttaa tää muuttuja. Toi then() syntaxi ei mun mielestä myöskään oo yhtä selkee kun async/await. 

Mä ymmärtäisin helpommin mitä tässä tapahtuu jos se ois muotoiltu jotenki näin: 
```typescript
const response = await openai...
const completion = response.choices[0].message.content
return completion
```

Ois myös jees jos ton vastauksen sais tyypitettynä, niin tän funktion return tyypin sais kans, jolloin tätä funktioo ois helpompi käyttää. Veikaan et OpenAi tarjoo tyypit.

Typescript ei tainnu olla viel kovin tuttu, niin jos menee hankalaks voin yrittää miettii noita tyyppejä ite.

2023-10-23 07:54 UTC, rhiskk approved these changes
👍

2023-10-23 08:04 UTC, merged